version: "3.3"
services:
  mysqldb:
    container_name: mysqldb
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 22Qqwwee
      MYSQL-DATABASE:  upendardb
      MYSQL_USER: upendar_user
      MYSQL_PASSWORD: upendar_pass
      MYSQL_TCP_PORT: 3306
    ports:
      - "3306:3306"
    networks:
      - my-net


  backend-container:
    container_name: backend-container
    build:
      context: .
      dockerfile: Dockerfile 
    ports:
      - "8000:8000"
    depends_on: 
      - mysqldb 
    networks:
      - my-net
    restart: on-failure 

networks:
  my-net: 
    driver: bridge 


  
